### ISSUE TITLE
Provide binaries distributions

### ISSUE THREAD

**Issue by davidmpaz** [hoffie/sshified#1]
Hi,

thanks for open sourcing this piece of work, i am trying to set up a small project of mine with Prometheus and did found your presentation on PromCon very useful. 

Would it be possible to make releases with a binary distribution, at least for a general linux distribution?

I am asking because i am a complete ignorant of the GO ecosystem, setting up the complete stack may be a lot effort to invest to solve one part of my current goals.

Thanks again in advance for your time,
Cheers,
David

**Comment by hoffie** [comment]
Thanks for the feedback!
This should certainly be possible, but I currently lack the time to do so. I guess one could come up with a release workflow based on Github actions. I'd be certainly open to that! :)

**Comment by hoffie** [comment]
Well, ironically, I've just implemented this as a side-product of my target to provide official Github releases, see here:
https://github.com/hoffie/sshified/releases :)
